---
- hosts: all
  tasks:
          - name: "Installing httpd software"
            package:
                    name: "httpd"
                    state: "present"
          - name: "Deploying webpages"
            copy:
                    src: "index.html"
                    dest: "/var/www/html/index.html"
          - name: "Configuring httpd configuration files"
            replace:
                    path: "/etc/httpd/conf/httpd.conf"
                    regexp: "AllowOverride None"
                    replace: "AllowOverride AuthConfig"
          - name: "Copying .htaccess file "
            copy:
                    dest: "/var/www/html/.htaccess"
                    src: ".htaccess"
          - name: "Configuring htpasswd file"
            path: "/etc/www.passwd"
            name: "test_user"
            password: "test_pass"
          - name: "Restarting web server services"
            service:
                    name: "httpd"
                    state: "restarted"
                    enabled: "yes"
